// Start browser-server.mjs in the same execution environment first.
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {mkdirSync,readFileSync} from 'node:fs';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||`${process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES}/playwright`);
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--single-process','--no-zygote']});
const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();
const origin='http://localhost:4173',shots=process.env.SCREENSHOT_DIR||'/tmp/privateoffice-shots';mkdirSync(shots,{recursive:true});
for(let attempt=0;attempt<80;attempt++){try{const r=await fetch(origin+'/__test/fixture');if(r.ok)break}catch{}await new Promise(r=>setTimeout(r,250));}
const errors=[];page.on('pageerror',e=>errors.push(e.message));const fixture=await(await page.request.get(origin+'/__test/fixture')).json();
try{
 await page.goto(origin);await page.getByRole('button',{name:'Make an enquiry'}).waitFor();
 for(const width of [375,768,1440]){await page.setViewportSize({width,height:900});await page.screenshot({path:`${shots}/home-${width}.png`});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`homepage overflow at ${width}`)}
 console.log('PASS homepage responsive at 375, 768, 1440');
 await page.getByRole('button',{name:'Make an enquiry'}).click();await page.getByLabel('Your name').fill('Synthetic Buyer');await page.getByLabel('Email or phone').fill('buyer@example.invalid');await page.getByLabel('What are you looking for?').fill('Synthetic QA enquiry for a private off-plan presentation.');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Send enquiry'}).click();await page.getByText('We have your enquiry.').waitFor();console.log('PASS buyer enquiry receipt');
 await page.goto(origin+fixture.screeningPath);await page.getByRole('heading',{name:'Share where you are working from.'}).waitFor();
 const screeningCdp=await context.newCDPSession(page);await screeningCdp.send('Browser.setPermission',{permission:{name:'geolocation'},setting:'denied',origin});
 await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Share my working area',exact:true}).click();await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),/denied/);await page.screenshot({path:`${shots}/screening-denied.png`});
 await context.grantPermissions(['geolocation']);await context.setGeolocation({latitude:-17.79,longitude:31.06,accuracy:7});await page.reload();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Share my working area',exact:true}).click();await page.getByLabel('Full name',{exact:true}).waitFor();
 await context.setGeolocation({latitude:-17.7801,longitude:31.071,accuracy:8});
 await page.getByText('Latest device fix ±8 m',{exact:false}).waitFor();
 await page.getByRole('button',{name:'Stop sharing',exact:true}).click();
 if(await page.getByRole('button',{name:'Retry pending coordinates'}).count())await page.getByRole('button',{name:'Retry pending coordinates'}).click();
 await page.getByRole('button',{name:'Share my working area',exact:true}).click();
 console.log('PASS moving screening captures fixes and explicit stop/resume');
 await page.getByLabel('Full name',{exact:true}).fill('Synthetic Candidate');await page.getByLabel('Phone',{exact:true}).fill('+263700000002');await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByLabel('City',{exact:true}).fill('Harare');await page.getByLabel('Country',{exact:true}).fill('Zimbabwe');await page.getByLabel('Languages — separated by commas').fill('English, Shona');await page.getByLabel('Markets worked — separated by commas').fill('Zimbabwe, UAE');await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByLabel('Years in property').fill('5');await page.getByLabel('Property specialisms — separated by commas').fill('Off-plan');await page.getByLabel('A transaction or client brief you handled').fill('Synthetic scenario: I managed a residential brief with documented diligence and buyer follow-up.');await page.getByLabel('What would you bring to Private Office?').fill('Synthetic professional response about discretion and independent verification.');await page.getByRole('button',{name:'Save background & begin'}).click();
 await page.getByRole('radio').first().check();await page.getByRole('button',{name:'Save & next',exact:true}).click();await page.getByText('Scenario 2 of',{exact:false}).waitFor();await page.reload();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Share my working area',exact:true}).click();await page.getByText('Scenario 2 of',{exact:false}).waitFor();await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'screening mobile overflow');await page.screenshot({path:`${shots}/screening-mobile.png`,fullPage:true});await page.setViewportSize({width:1440,height:1000});console.log('PASS screening GPS denial, acquisition and saved response recovery');
 const screening=(await(await page.request.get(origin+'/api'+fixture.screeningPath)).json()).screening;
 for(let n=1;n<screening.questions.length;n++){await page.getByText(`Scenario ${n+1} of`,{exact:false}).waitFor();await page.getByRole('radio').first().check();await page.getByRole('button',{name:n===screening.questions.length-1?'Save & review':'Save & next',exact:true}).click();}
 await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Submit for review',exact:true}).click();await page.getByRole('heading',{name:'Your introduction is with the office.'}).waitFor();await page.screenshot({path:`${shots}/screening-complete.png`});console.log('PASS interactive screening submission');
 await context.addCookies([{name:'qa_reviewer',value:'1',url:origin}]);
 const reviewer=await context.newPage();await reviewer.goto(origin+'/office');
 await reviewer.getByText('Location history',{exact:true}).first().click();
 await reviewer.getByText('-17.780100, 31.071000',{exact:true}).first().waitFor();
 const downloadWait=reviewer.waitForEvent('download');await reviewer.getByRole('button',{name:'Download all coordinates (CSV)'}).first().click();const download=await downloadWait;assert.match(download.suggestedFilename(),/screening-coordinates/);const csv=readFileSync(await download.path(),'utf8');assert.match(csv,/-17.7801/);assert.match(csv,/recorded_at,received_at/);
 await reviewer.close();await context.clearCookies({name:'qa_reviewer'});console.log('PASS reviewer coordinate stream and CSV export');
 await page.goto(origin+'/agent/sign-in');await page.screenshot({path:`${shots}/sign-in.png`});await page.getByLabel('Username',{exact:true}).fill(fixture.username);await page.getByLabel('Password',{exact:true}).fill(fixture.password);await page.getByRole('button',{name:'Enter Private Office'}).click();await page.waitForURL('**/agent/onboarding');
 await page.goto(origin+'/residences');await page.getByRole('heading',{level:1}).waitFor();await page.screenshot({path:`${shots}/collection.png`});await page.goto(origin+'/residences/tierra-viva');await page.getByRole('heading',{level:1}).waitFor();await page.screenshot({path:`${shots}/project.png`});
 await page.goto(origin+'/agent/onboarding');
 await page.getByLabel('Preferred professional name').fill('Synthetic Agent');await page.getByLabel('Contact telephone').fill('+263700000000');await page.getByLabel('Professional base / city').fill('Harare');await page.getByLabel('Working languages').fill('English, Shona');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Save & continue',exact:true}).click();await page.getByRole('heading',{name:'Identity & background',exact:true}).waitFor();await page.reload();await page.getByLabel('Preferred professional name').waitFor();assert.equal(await page.getByLabel('Preferred professional name').inputValue(),'Synthetic Agent');console.log('PASS sign-in and saved profile recovery');
 const titles=['Identity & background','Off-plan expertise','Service & discretion','Professional judgment','Territory & availability'];
 for(const title of titles){await page.getByRole('button',{name:new RegExp(title.replace('&','&'))}).click();const areas=page.locator('textarea');for(let i=0;i<await areas.count();i++)await areas.nth(i).fill('Synthetic assessment response: independently verify project documents, disclose uncertainties, maintain confidentiality and escalate decisions to the office.');await page.getByRole('button',{name:'Save for later'}).click();await page.getByText('Progress saved. You can safely return later.').waitFor();}
 await page.screenshot({path:`${shots}/interview.png`});await page.getByRole('button',{name:'Submit for review'}).click();await page.getByText('With our team for review',{exact:true}).waitFor();console.log('PASS five interview stages and submission');
 await context.addCookies([{name:'qa_reviewer',value:'1',url:origin}]);await page.goto(origin+'/office/reviews');await page.getByRole('button',{name:'Read professional profile'}).click();for(const select of await page.getByLabel('Current level').all())await select.selectOption('2');for(const area of await page.getByLabel('Review notes').all())await area.fill('Synthetic test reviewer verified the answer against professional criteria.');await page.getByLabel('Agent feedback, conditions and assignment guidance').fill('Synthetic approval: supervised initial client assignment and reviewed due diligence.');for(const check of await page.getByRole('checkbox').all())await check.check();await page.screenshot({path:`${shots}/review.png`});await page.getByRole('button',{name:'Approve for assignments'}).click();await page.getByText('Profile approved. The agent can now access visits.').waitFor();console.log('PASS human review and classification');await context.clearCookies({name:'qa_reviewer'});
 await page.goto(origin+'/agent');await page.getByRole('button',{name:'Start visit',exact:true}).waitFor();await context.grantPermissions(['geolocation']);await context.setGeolocation({latitude:-17.79,longitude:31.06,accuracy:7});await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Start visit',exact:true}).click();await page.getByText('±7 m · Excellent',{exact:true}).waitFor();await page.screenshot({path:`${shots}/gps-success.png`});await page.getByRole('button',{name:'Pause visit',exact:true}).click();await page.getByRole('button',{name:'Start visit',exact:true}).waitFor();console.log('PASS permission granted GPS observation and stop');
 await context.clearPermissions();const cdp=await context.newCDPSession(page);await cdp.send('Browser.setPermission',{permission:{name:'geolocation'},setting:'denied',origin});await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Start visit',exact:true}).click();await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),/permission|denied|blocked/i);await page.screenshot({path:`${shots}/gps-denied.png`});console.log('PASS permission denied shows actionable error');await context.grantPermissions(['geolocation'],{origin});await context.setGeolocation({latitude:-17.79,longitude:31.06,accuracy:7});await page.reload();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Start visit',exact:true}).click();await page.getByRole('button',{name:'End visit',exact:true}).click();await page.getByText('This visit is closed.',{exact:true}).waitFor();console.log('PASS explicit end closes visit');assert.deepEqual(errors,[],'browser page errors');console.log('PASS no browser page errors');
}catch(e){await page.screenshot({path:`${shots}/failure.png`});console.log((await page.locator('body').innerText()).slice(-6000));throw e}finally{await browser.close()}
