import {env} from 'cloudflare:workers';
import {headers} from 'next/headers';
import {redirect} from 'next/navigation';
export type ChatGPTUser={userId:string;displayName:string;email:string;fullName:string|null};
const USER_ID_HEADER='oai-authenticated-user-id',USER_EMAIL_HEADER='oai-authenticated-user-email',USER_FULL_NAME_HEADER='oai-authenticated-user-full-name',USER_FULL_NAME_ENCODING_HEADER='oai-authenticated-user-full-name-encoding',PERCENT_ENCODED_UTF8='percent-encoded-utf-8',SIGN_IN_PATH='/signin-with-chatgpt',SIGN_OUT_PATH='/signout-with-chatgpt',CALLBACK_PATH='/callback';
type AccessPayload={sub?:string;email?:string;name?:string;iss?:string;aud?:string|string[];exp?:number;nbf?:number};
let jwksCache:{url:string;expires:number;keys:any[]}|null=null;
function bytes(value:string){const s=value.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(value.length/4)*4,'=');const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
function decodePart<T>(part:string):T{return JSON.parse(new TextDecoder().decode(bytes(part)))}
function teamDomain(value:string){const trimmed=value.trim().replace(/\/$/,'');return trimmed.startsWith('http')?trimmed:`https://${trimmed}`}
async function keysFor(team:string){const url=team+'/cdn-cgi/access/certs',now=Date.now();if(jwksCache?.url===url&&jwksCache.expires>now)return jwksCache.keys;const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('Cloudflare Access signing keys unavailable.');const data=await r.json() as {keys?:any[]};if(!Array.isArray(data.keys))throw new Error('Cloudflare Access signing keys invalid.');jwksCache={url,keys:data.keys,expires:now+5*60*1000};return data.keys}
async function verifyAccess(token:string,team:string,audience:string):Promise<AccessPayload>{const parts=token.split('.');if(parts.length!==3)throw new Error('Invalid Access token.');const header=decodePart<{alg?:string;kid?:string}>(parts[0]),payload=decodePart<AccessPayload>(parts[1]);if(header.alg!=='RS256'||!header.kid)throw new Error('Unsupported Access token.');const jwk=(await keysFor(team)).find(k=>k.kid===header.kid);if(!jwk)throw new Error('Access signing key not found.');const key=await crypto.subtle.importKey('jwk',jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);const ok=await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,bytes(parts[2]),new TextEncoder().encode(parts[0]+'.'+parts[1]));if(!ok)throw new Error('Access token signature invalid.');const now=Math.floor(Date.now()/1000);if(payload.iss!==team)throw new Error('Access issuer mismatch.');const aud=Array.isArray(payload.aud)?payload.aud:[payload.aud].filter(Boolean);if(!aud.includes(audience))throw new Error('Access audience mismatch.');if(!payload.exp||payload.exp<=now)throw new Error('Access token expired.');if(payload.nbf&&payload.nbf>now+30)throw new Error('Access token is not active.');return payload}
export async function getChatGPTUser():Promise<ChatGPTUser|null>{const requestHeaders=await headers();const runtime=env as any;const standalone=runtime.PRIVATE_OFFICE_STANDALONE==='1';const accessTeam=runtime.CF_ACCESS_TEAM_DOMAIN as string|undefined,accessAud=runtime.CF_ACCESS_AUD as string|undefined;
if(standalone){if(!accessTeam||!accessAud)return null;const token=requestHeaders.get('cf-access-jwt-assertion');if(!token)return null;try{const payload=await verifyAccess(token,teamDomain(accessTeam),accessAud);if(!payload.sub||!payload.email)return null;return {userId:payload.sub,email:payload.email,displayName:payload.name||payload.email,fullName:payload.name||null}}catch(e){console.error('Cloudflare Access verification failed',e instanceof Error?e.message:'unknown');return null}}
const userId=requestHeaders.get(USER_ID_HEADER),email=requestHeaders.get(USER_EMAIL_HEADER);if(!userId||!email)return null;const encodedFullName=requestHeaders.get(USER_FULL_NAME_HEADER),fullName=encodedFullName&&requestHeaders.get(USER_FULL_NAME_ENCODING_HEADER)===PERCENT_ENCODED_UTF8?safeDecodeURIComponent(encodedFullName):null;return {userId,displayName:fullName??email,email,fullName}}
export async function requireChatGPTUser(returnTo:string){const user=await getChatGPTUser();if(user)return user;redirect(chatGPTSignInPath(returnTo))}
export function chatGPTSignInPath(returnTo:string){const safe=safeRelativeReturnPath(returnTo);return `${SIGN_IN_PATH}?return_to=${encodeURIComponent(safe)}`}
export function chatGPTSignOutPath(returnTo='/'){const safe=safeRelativeReturnPath(returnTo);return `${SIGN_OUT_PATH}?return_to=${encodeURIComponent(safe)}`}
function safeRelativeReturnPath(value:string){if(!value.startsWith('/')||value.startsWith('//'))return '/';let url:URL;try{url=new URL(value,'https://app.local')}catch{return '/'}if(url.origin!=='https://app.local'||isReservedAuthPath(url.pathname))return '/';return `${url.pathname}${url.search}${url.hash}`}
function isReservedAuthPath(pathname:string){return pathname===SIGN_IN_PATH||pathname===SIGN_OUT_PATH||pathname===CALLBACK_PATH}
function safeDecodeURIComponent(value:string){try{return decodeURIComponent(value)}catch{return null}}
