'use client';
import {useEffect,useState} from 'react';
import {api,post} from '@/lib/client';
import {stages,profileKeys,completeness,requiredCount,type ScreeningData} from '@/lib/interview';
import type {Onboarding} from '@/lib/onboarding';
import AgentHeader from './agent-header';
import './screening.css';
const profileLabels:Record<string,string>={preferredName:'Preferred professional name',phone:'Contact telephone',base:'Professional base / city',languages:'Working languages'};
export default function AgentOnboarding(){
 const [record,setRecord]=useState<Onboarding|null>(null),[data,setData]=useState<ScreeningData|null>(null),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false);
 async function load(){setError('');try{const result=await api<{onboarding:Onboarding}>('/api/agent/onboarding');setRecord(result.onboarding);setData(result.onboarding.data);setDirty(false)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{let cancelled=false;api<{onboarding:Onboarding}>('/api/agent/onboarding').then(result=>{if(!cancelled){setRecord(result.onboarding);setData(result.onboarding.data)}}).catch(e=>{if(!cancelled)setError((e as Error).message)});return()=>{cancelled=true}},[]);
 useEffect(()=>{if(!dirty)return;const prevent=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent)},[dirty]);
 function update(group:'profile'|'answers',key:string,value:string){setData(d=>d?{...d,[group]:{...d[group],[key]:value}}:d);setDirty(true);setMessage('')}
 async function save(action:'save'|'submit',advance=false){if(!record||!data)return;setBusy(true);setError('');setMessage('');try{const result=await post('/api/agent/onboarding',{action,data,revision:record.revision});setRecord(result.onboarding);setData(result.onboarding.data);setDirty(false);setMessage(action==='submit'?'Submitted. Our team will review your introduction before visits are activated.':'Progress saved. You can safely return later.');if(advance)setStep(s=>Math.min(s+1,5))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const locked=record?.status==='submitted'||record?.status==='approved';
 return <><AgentHeader/><main className="app-main screening-main"><div className="app-title"><div><p className="eyebrow">INVITED AGENT · PRIVATE OFFICE</p><h1>Your professional introduction.</h1><p className="muted">Tell us how you work. We use your answers to match your expertise to the right clients and assignments.</p></div></div>
 {error&&<p className="error" role="alert">{error}</p>}{!record||!data?<div className="section-gap"><p role="status">{error?'Your profile could not be loaded.':'Loading your introduction…'}</p>{error&&<button className="button" onClick={load}>Retry</button>}</div>:<>
 <div className="screening-status" role="status"><strong>{record.status==='draft'?'Introduction in progress':record.status==='submitted'?'With our team for review':record.status==='changes_requested'?'Further information requested':'Approved for assignments'}</strong><span>{completeness(data)} of {requiredCount} required items complete{dirty?' · Unsaved changes':''}</span></div>
 {record.feedback&&<div className="notice section-gap"><strong>Team feedback</strong><p>{record.feedback}</p>{record.classification&&<p>Assessed expertise: {record.classification}</p>}</div>}
 {locked?<section className="screening-content"><h2>{record.status==='approved'?'Welcome to the office.':'Thank you for your introduction.'}</h2><p>{record.status==='approved'?'Your profile has been reviewed. You can now access assigned visits.':'Your answers are saved while a member of our team looks over your experience, references and agreement. They'll either activate your profile or ask for anything else they need. No automated system makes that decision.'}</p><a className="button" href={record.status==='approved'?'/agent':'/residences'}>{record.status==='approved'?'Open assigned visits':'Explore the property collection'}</a><button className="button outline" onClick={load}>Refresh status</button></section>:<div className="screening-layout">
 <nav className="screening-steps" aria-label="Interview stages">{['Welcome & profile',...stages.map(s=>s.title)].map((title,index)=><button key={title} type="button" aria-current={step===index?'step':undefined} onClick={()=>setStep(index)}><span>{String(index+1).padStart(2,'0')}</span>{title}</button>)}</nav>
 <form className="screening-content" onSubmit={e=>{e.preventDefault();void save('save',true)}}>
 {step===0?<><p className="eyebrow">FIRST LOGIN</p><h2>Welcome to Private Office.</h2><p>This introduction is for handpicked agents with office-issued credentials. Complete the five written interview stages at your own pace. Save each stage before leaving.</p><p className="muted">We look at property knowledge, client care and professional judgment using a clear development guide: building, developing, practitioner or specialist. Territory and availability help us match assignments. Your answers are visible to you and our review team; please avoid client names, confidential files or identity-document numbers.</p><div className="form-grid">{profileKeys.map(k=><label key={k}>{profileLabels[k]}<input value={data.profile[k]||''} maxLength={200} autoComplete={k==='phone'?'tel':k==='preferredName'?'name':'off'} type={k==='phone'?'tel':'text'} onChange={e=>update('profile',k,e.target.value)}/></label>)}</div><label className="screening-check"><input type="checkbox" checked={data.acknowledged} onChange={e=>{setData({...data,acknowledged:e.target.checked});setDirty(true)}}/><span>I confirm that Private Office invited me, that I have a signed agency agreement, and that the professional information I provide is accurate. Our team will confirm eligibility before activation.</span></label></>:<><p className="eyebrow">INTERVIEW {step} OF 5</p><h2>{stages[step-1].title}</h2><p className="muted">What we're looking for: {stages[step-1].assesses}</p>{stages[step-1].questions.map(q=><label key={q.id}>{q.label}<textarea rows={6} maxLength={4000} value={data.answers[q.id]||''} onChange={e=>update('answers',q.id,e.target.value)}/><small>{(data.answers[q.id]||'').length}/4000 characters</small></label>)}</>}
 {message&&<p className="success" role="status">{message}</p>}<div className="actions"><button className="button" type="submit" disabled={busy}>{busy?'Saving…':step===5?'Save progress':'Save & continue'}</button><button className="button outline" type="button" disabled={busy} onClick={()=>save('save')}>Save for later</button></div>
 {step===5&&<div className="screening-submit"><p>Submit when all stages are complete. Your answers will stay unchanged while a member of our team reviews them. This does not automatically approve your profile.</p><button className="button" type="button" disabled={busy||completeness(data)!==requiredCount} onClick={()=>save('submit')}>Submit for review</button>{completeness(data)!==requiredCount&&<p className="muted">Finish the remaining {requiredCount-completeness(data)} items in the earlier stages.</p>}</div>}
 </form></div>}</>}
 </main></>;
}
