'use client';
import {useEffect,useState} from 'react';
import {api,post} from '@/lib/client';
import {stages,profileKeys,rubric,ratingLabels,classification} from '@/lib/interview';
import type {Onboarding} from '@/lib/onboarding';
import './screening.css';
type SavedReview={scores:Record<string,number>;evidence:Record<string,string>;feedback:string;classification:string;identity_verified:boolean;contract_verified:boolean};
type Entry={id:string;full_name:string;email:string;onboarding:Onboarding;review:SavedReview|null};
export default function AgentReviews(){
 const [agents,setAgents]=useState<Entry[]>([]),[selected,setSelected]=useState<Entry|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[scores,setScores]=useState<Record<string,number>>({}),[evidence,setEvidence]=useState<Record<string,string>>({}),[feedback,setFeedback]=useState(''),[identity,setIdentity]=useState(false),[contract,setContract]=useState(false);
 async function load(){setLoading(true);try{const result=await api<{agents:Entry[]}>('/api/office/reviews');setAgents(result.agents);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{let cancelled=false;api<{agents:Entry[]}>('/api/office/reviews').then(result=>{if(!cancelled)setAgents(result.agents)}).catch(e=>{if(!cancelled)setError((e as Error).message)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[]);
 function select(a:Entry){setSelected(a);setScores({});setEvidence({});setFeedback('');setIdentity(false);setContract(false);setMessage('');setError('')}
 async function decide(decision:string){if(!selected)return;setBusy(true);setError('');try{await post('/api/office/reviews',{agent_id:selected.id,revision:selected.onboarding.revision,decision,scores,evidence,feedback,identity_verified:identity,contract_verified:contract});setMessage(decision==='approved'?'Profile approved. The agent can now access visits.':'Feedback saved. The agent can revise and resubmit.');setSelected(null);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="app-main screening-main"><a className="text-link" href="/office">← Office workspace</a><div className="app-title"><div><p className="eyebrow">OFFICE · AGENT INTRODUCTIONS</p><h1>Agent introduction.</h1><p className="muted">Read through the agent’s experience, add useful notes and decide the next step for assignments.</p></div></div>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}
 {!selected?<div className="review-queue">{loading?<p role="status">Loading agent profiles…</p>:agents.length===0?<p>No invited agents yet. Create office-issued credentials in the office workspace.</p>:agents.map(a=><section className="review-agent" key={a.id}><h2>{a.full_name}</h2><p>{a.email}</p><p className="muted">{a.onboarding.status.replaceAll('_',' ')}{a.onboarding.classification?' · '+a.onboarding.classification:''}</p><button className="button outline section-gap" onClick={()=>select(a)}>Read professional profile</button></section>)}<button className="button outline" onClick={load}>Refresh</button></div>:<section className="screening-content"><button className="button outline" onClick={()=>setSelected(null)}>Back to agents</button><h2>{selected.full_name}</h2><p>Status: {selected.onboarding.status.replaceAll('_',' ')}</p><dl>{profileKeys.map(k=><div className="review-question" key={k}><dt>{k.replace(/([A-Z])/g,' $1')}</dt><dd className="review-answer">{selected.onboarding.data.profile[k]||'Not provided'}</dd></div>)}</dl>{stages.map(stage=><section key={stage.id}><h2>{stage.title}</h2>{stage.questions.map(q=><div className="review-question" key={q.id}><strong>{q.label}</strong><p className="review-answer">{selected.onboarding.data.answers[q.id]||'Not answered'}</p></div>)}</section>)}
 {selected.review&&<section className="screening-content" aria-label="Saved review"><h2>Team summary</h2><p><strong>Strengths profile: {selected.review.classification}</strong></p><p className="muted">These levels were added by a team member using the agent’s answers and the details checked during the introduction. Experience described by the agent remains their own account.</p>{rubric.map(r=><div className="review-question" key={r.id}><h3>{r.label}</h3><p>{ratingLabels[selected.review!.scores[r.id]]||'Not yet clear'}</p><p className="review-answer">{selected.review!.evidence[r.id]||'No note added.'}</p></div>)}<p>Identity and eligibility: {selected.review.identity_verified?'Confirmed':'Not yet confirmed'}<br/>Signed agreement: {selected.review.contract_verified?'Confirmed':'Not yet confirmed'}</p><div className="notice"><strong>Assignment guidance & feedback</strong><p>{selected.review.feedback}</p></div></section>}
 {selected.onboarding.status==='submitted'?<form className="screening-content" onSubmit={e=>{e.preventDefault();void decide('approved')}}><h2>Next step</h2><p>Use only information relevant to the role. The strengths summary helps organize the conversation; it does not decide the outcome. A developing agent can still move forward with clear support or supervision notes.</p>{rubric.map(r=><fieldset className="screening-content" key={r.id}><legend>{r.label}</legend><label>Current level<select required value={scores[r.id]??''} onChange={e=>setScores({...scores,[r.id]:Number(e.target.value)})}><option value="" disabled>Choose a level</option>{ratingLabels.map((label,i)=><option key={i} value={i}>{label}</option>)}</select></label><label>Team notes<textarea required minLength={10} maxLength={2000} rows={3} value={evidence[r.id]||''} onChange={e=>setEvidence({...evidence,[r.id]:e.target.value})}/></label></fieldset>)}<p><strong>Strengths summary: {classification(scores)}</strong></p><label>Agent feedback and assignment guidance<textarea required minLength={10} maxLength={3000} rows={4} value={feedback} onChange={e=>setFeedback(e.target.value)}/></label><label className="screening-check"><input type="checkbox" checked={identity} onChange={e=>setIdentity(e.target.checked)}/><span>I have confirmed the agent’s identity and eligibility for assignments.</span></label><label className="screening-check"><input type="checkbox" checked={contract} onChange={e=>setContract(e.target.checked)}/><span>I have confirmed the agency agreement is in place.</span></label><div className="actions"><button className="button" disabled={busy||!identity||!contract} type="submit">{busy?'Saving…':'Approve for assignments'}</button><button className="button outline" disabled={busy} type="button" onClick={()=>decide('changes_requested')}>Request further information</button></div></form>:<p className="notice">{selected.onboarding.status==='approved'?'This agent is ready for assignments.':'The agent needs to submit their introduction before the team can decide the next step.'}{selected.onboarding.feedback?' Team feedback: '+selected.onboarding.feedback:''}</p>}
 </section>}</main>
}
