/* Native navigation is intentional: Vinext client Link crashed in production; see PRODUCTION_RECOVERY_2026-09-28.md. */
/* eslint-disable @next/next/no-html-link-for-pages */
'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,LoaderCircle} from 'lucide-react';
import {api,post} from '@/lib/client';
import ScreeningCheckIn from './screening-check-in';
import styles from './agent-onboarding.module.css';
type Question={id:string;stage:string;prompt:string;choices:{id:string;label:string}[]};
type Classification={version:string;archetype:string;primary_strengths:string[];interview_focus:string[];dimensions:Record<string,{score:number;level:string}>};
type Application={id:string;status:string;full_name?:string;email?:string;phone?:string;city?:string;country?:string;current_company?:string|null;years_experience?:number;languages?:string[];markets?:string[];specialisms?:string[];experience_summary?:string;motivation?:string;answers?:Record<string,string>;classification?:Classification|null};
type Payload={invite:{status:string;intended_email?:string|null;expires_at:number};application:Application|null;screening:{questions:Question[]};location:{status:string;accuracy:number|null;received_at:number|null;expires_at:number|null}};
const LABELS:Record<string,string>={off_plan:'Off-plan',client_advisory:'Client advisory',deal_execution:'Deal execution',international:'International',compliance:'Compliance',operating_discipline:'Operating discipline'};
const STAGES:Record<string,string>={property:'Your property judgment',judgment:'Client trust & discretion',operations:'How you work'};
const empty={full_name:'',email:'',phone:'',city:'',country:'',current_company:'',years_experience:'',languages:'',markets:'',specialisms:'',experience_summary:'',motivation:''};
function csv(value:string){return [...new Set(value.split(',').map(x=>x.trim()).filter(Boolean))]}
export default function AgentOnboarding({token}:{token:string}){
 const [data,setData]=useState<Payload|null>(null),[profile,setProfile]=useState(empty),[answers,setAnswers]=useState<Record<string,string>>({});
 const [step,setStep]=useState(0),[part,setPart]=useState(0),[index,setIndex]=useState(0),[ready,setReady]=useState(false);
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[declared,setDeclared]=useState(false);
 const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{let alive=true;api<Payload>('/api/onboarding/'+token).then(d=>{if(!alive)return;setData(d);setReady(d.location.status==='manual_approved');const a=d.application;if(a){setProfile({full_name:a.full_name||'',email:a.email||'',phone:a.phone||'',city:a.city||'',country:a.country||'',current_company:a.current_company||'',years_experience:String(a.years_experience??''),languages:(a.languages||[]).join(', '),markets:(a.markets||[]).join(', '),specialisms:(a.specialisms||[]).join(', '),experience_summary:a.experience_summary||'',motivation:a.motivation||''});setAnswers(a.answers||{});const next=d.screening.questions.findIndex(q=>!a.answers?.[q.id]);setIndex(next<0?0:next);setStep(next<0?2:1)}else setProfile(p=>({...p,email:d.invite.intended_email||''}))}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[token]);
 useEffect(()=>{heading.current?.focus()},[step,part,index,ready]);
 async function save(action:string,values:Record<string,unknown>){setBusy(true);setError('');try{const r=await post('/api/onboarding/'+token,{action,...values}) as {application:Application};setData(d=>d?{...d,application:r.application}:d);setNotice('Progress saved. You can return using this invitation.');return true}catch(e){const message=(e as Error).message;setError(message);if(/screening location|manual interview/i.test(message))setReady(false);return false}finally{setBusy(false)}}
 async function saveProfile(event:FormEvent){event.preventDefault();if(part<2){setPart(part+1);return}if(await save('save_profile',{...profile,years_experience:Number(profile.years_experience),languages:csv(profile.languages),markets:csv(profile.markets),specialisms:csv(profile.specialisms)})){setStep(1);setIndex(0)}}
 async function nextQuestion(){const q=data!.screening.questions[index];if(!answers[q.id]){setError('Choose the response closest to your approach.');return}if(await save('save_answers',{answers:{[q.id]:answers[q.id]}})){if(index+1===data!.screening.questions.length)setStep(2);else setIndex(index+1)}}
 async function submit(){if(!declared)return;await save('submit',{declaration:true})}
 async function checked(location:{status:string;accuracy:number|null;received_at:number|null}){setData(d=>d?{...d,location:{...location,expires_at:location.received_at?location.received_at+900000:null}}:d);setReady(true);setError('')}
 function locationStopped(){if(data?.location.status!=='manual_approved')setReady(false)}
 function field(key:keyof typeof empty,label:string,options:{type?:string;minLength?:number;optional?:boolean}={}){return <label key={key}>{label}{options.minLength?<textarea required minLength={options.minLength} maxLength={1200} value={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.value})}/>:<input type={options.type||'text'} required={!options.optional} min={options.type==='number'?0:undefined} max={options.type==='number'?60:undefined} maxLength={160} value={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.value})}/>}</label>}
 if(!data)return <main className={styles.loading}>{error?<><h1>Invitation unavailable</h1><p role="alert">{error}</p><a href="/">Return to Private Office</a></>:<><LoaderCircle className={styles.spin}/><p>Opening your invitation…</p></>}</main>;
 const locked=!!data.application&&data.application.status!=='draft',questions=data.screening.questions,q=questions[index];
 return <main className={styles.shell}><header className={styles.header}><a href="/" className={styles.wordmark}><b>╱</b><span>PRIVATE OFFICE<small>PROPERTY & PEOPLE</small></span></a><span>YOUR PROFESSIONAL INTRODUCTION</span></header>
 {locked?<><section className={styles.completeHero}><p className={styles.eyebrow}>{data.application!.status.toUpperCase()}</p><h1>Your introduction is with the office.</h1><p>A person reviews your experience, scenario responses and screening location evidence. Credentials and activation are handled separately; this interview does not automatically approve or reject you.</p></section>{data.application!.classification&&<ClassificationView classification={data.application!.classification}/>}</>:<>
 <section className={styles.conversationIntro}><p className={styles.eyebrow}>THOUGHTFUL PROPERTY. THOUGHTFUL PEOPLE.</p><h1>Let’s get to know<br/><em>how you work.</em></h1><p>A few professional details, then short client scenarios. Choose your approach, save as you go, and leave the final judgment to our team.</p></section>
 <ScreeningCheckIn token={token} onReady={checked} onStopped={locationStopped} active={ready}/>{ready&&<section className={styles.conversation}>
 <div className={styles.conversationMeta}><span>{step===0?'01 · YOUR BACKGROUND':step===1?'02 · CLIENT SCENARIOS':'03 · YOUR INTRODUCTION'}</span><span>{data.location.status==='manual_approved'?'Manual interview approved':`Location stream · ±${Math.round(data.location.accuracy||0)} m`}</span></div>
 <progress aria-label="Interview progress" max={questions.length+3} value={step===0?part:step===1?3+Object.keys(answers).length:questions.length+3}/>
 <h2 ref={heading} tabIndex={-1}>{step===0?['Start with your introduction.','Where do you advise?','Tell us about your practice.'][part]:step===1?STAGES[q.stage]||'Your approach':'Ready for a conversation?'}</h2>
 {step===0&&<form onSubmit={saveProfile} className={styles.profileForm}>
 {part===0&&<>{field('full_name','Full name')}{field('email','Professional email',{type:'email'})}{field('phone','Phone')}{field('current_company','Company or independent status (optional)',{optional:true})}</>}
 {part===1&&<>{field('city','City')}{field('country','Country')}{field('languages','Languages — separated by commas')}{field('markets','Markets worked — separated by commas')}</>}
 {part===2&&<>{field('years_experience','Years in property',{type:'number'})}{field('specialisms','Property specialisms — separated by commas')}{field('experience_summary','A transaction or client brief you handled',{minLength:40})}{field('motivation','What would you bring to Private Office?',{minLength:30})}</>}
 <div className={styles.actions}>{part>0&&<button className={styles.secondary} type="button" onClick={()=>setPart(part-1)}>Back</button>}<button className={styles.primary} disabled={busy}>{busy?'Saving…':part<2?'Continue':'Save background & begin'}<ArrowRight size={17}/></button></div><p className={styles.saveNote}>Your background is saved after the third short step.</p></form>}
 {step===1&&<div className={styles.questions}><p className={styles.saveNote}>Scenario {index+1} of {questions.length} · Select one response. No timer.</p><fieldset key={q.id}><legend>{q.prompt}</legend>{q.choices.map(c=><label key={c.id} className={answers[q.id]===c.id?styles.selected:''}><input type="radio" disabled={busy} name={q.id} checked={answers[q.id]===c.id} onChange={()=>setAnswers({...answers,[q.id]:c.id})}/><span>{c.label}</span></label>)}</fieldset><div className={styles.actions}><button type="button" className={styles.secondary} disabled={busy} onClick={()=>index>0?setIndex(index-1):(setStep(0),setPart(0))}><ArrowLeft size={16}/>Back</button><button type="button" className={styles.primary} disabled={busy||!answers[q.id]} onClick={nextQuestion}>{busy?'Saving…':index+1===questions.length?'Save & review':'Save & next'}<ArrowRight size={16}/></button></div></div>}
 {step===2&&<div className={styles.review}><p>{profile.full_name} · {profile.city}, {profile.country}</p><p>{Object.keys(answers).length} of {questions.length} scenarios saved. We assess property knowledge, client discretion and operating judgment. This supports a human conversation, not an automatic decision.</p><button type="button" className={styles.secondary} onClick={()=>{setStep(0);setPart(0)}}>Review background</button><button type="button" className={styles.secondary} onClick={()=>{setStep(1);setIndex(0)}}>Review responses</button><label className={styles.declaration}><input type="checkbox" checked={declared} onChange={e=>setDeclared(e.target.checked)}/><span>I confirm my responses are accurate and agree to office review.</span></label><button type="button" className={styles.primary} disabled={busy||!declared} onClick={submit}>{busy?'Submitting…':'Submit for office review'}</button></div>}
 <p role="status" className={styles.saveNote}>{notice}</p>{error&&<p className={styles.error} role="alert">{error}</p>}
 </section>}
 </>}<footer className={styles.footer}><span>PRIVATE OFFICE · CONFIDENTIAL</span><a href="/privacy">Your data & location</a></footer></main>;
}
function ClassificationView({classification}:{classification:Classification}){return <section className={styles.classification}><div><p className={styles.eyebrow}>DESCRIPTIVE EXPERTISE MAP</p><h2>{classification.archetype}</h2><p>This map reflects your submitted scenario responses. The office reviews the full evidence, not a single total score.</p></div><div className={styles.dimensionList}>{Object.entries(classification.dimensions).map(([key,value])=><div key={key}><span>{LABELS[key]||key}</span><strong>{value.level}<small>{value.score}/100</small></strong></div>)}</div></section>}
