'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/client';
type Fix={id:string;source:string;lat:number;lng:number;accuracy:number;recorded_at:number;received_at:number;sequence_number?:number;session_id?:string;share_epoch?:string;speed?:number;heading?:number};
type Cursor={after:number;legacy_after:number};
type Page={rows:Fix[];next:Cursor;has_more:boolean};
const zero:Cursor={after:0,legacy_after:0};
function path(kind:string,id:string,cursor:Cursor){return '/api/office/coordinates?'+new URLSearchParams({kind,id,after:String(cursor.after),legacy_after:String(cursor.legacy_after)})}
export default function CoordinateHistory({kind,id}:{kind:'screening'|'visit';id:string}){
 const [open,setOpen]=useState(false),[rows,setRows]=useState<Fix[]>([]),[count,setCount]=useState(0),[error,setError]=useState(''),[updated,setUpdated]=useState<number|null>(null),[exporting,setExporting]=useState(false);
 useEffect(()=>{
  if(!open)return;let alive=true,timer:ReturnType<typeof setTimeout>;let cursor=zero;
  async function read(){try{const page=await api<Page>(path(kind,id,cursor));if(!alive)return;cursor=page.next;setRows(r=>[...r,...page.rows].sort((a,b)=>a.recorded_at-b.recorded_at||a.received_at-b.received_at).slice(-500));setCount(n=>n+page.rows.length);setUpdated(Date.now());setError('');timer=setTimeout(read,page.has_more?50:5000)}catch(e){if(alive){setError((e as Error).message);timer=setTimeout(read,10000)}}}
  void read();return()=>{alive=false;clearTimeout(timer)};
 },[open,kind,id]);
 async function download(){setExporting(true);setError('');try{let cursor=zero;const all:Fix[]=[];for(;;){const p=await api<Page>(path(kind,id,cursor));all.push(...p.rows);cursor=p.next;if(!p.has_more)break}all.sort((a,b)=>a.recorded_at-b.recorded_at||a.received_at-b.received_at);const fields:(keyof Fix)[]=['source','id','session_id','share_epoch','sequence_number','recorded_at','received_at','lat','lng','accuracy','speed','heading'];const escape=(v:unknown)=>'"'+(typeof v==='number'?String(v):String(v??'').replace(/^[=+@-]/,"'$&")).replaceAll('"','""')+'"';const csv=[fields.join(','),...all.map(r=>fields.map(k=>escape(r[k])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=kind+'-coordinates-'+id+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError((e as Error).message)}finally{setExporting(false)}}
 return <details className="section-gap" onToggle={e=>{setOpen(e.currentTarget.open);setRows([]);setCount(0);setUpdated(null)}}><summary>Location history</summary>{open&&<><p>Shared location updates, including movement where available. Refreshes every 5 seconds while open. {count} updates loaded; showing the latest {rows.length}. The download includes all saved location updates from the 30-day period, including earlier check-ins.</p><button type="button" className="button secondary" disabled={exporting} onClick={download}>{exporting?'Preparing…':'Download location history (CSV)'}</button><p role="status">{updated?'Last refreshed '+new Date(updated).toLocaleTimeString():'Loading location history…'}{rows.length?'':' · No shared locations yet.'}</p>{error&&<p role="alert">{error}</p>}<div className="points-scroll" style={{overflowX:'auto'}}><table><thead><tr><th>Device time</th><th>Location</th><th>Accuracy</th><th>Update reference</th><th>Saved</th></tr></thead><tbody>{rows.map(r=><tr key={r.source+':'+r.id}><td>{new Date(r.recorded_at).toISOString()}</td><td>{r.lat.toFixed(6)}, {r.lng.toFixed(6)}</td><td>±{Math.round(r.accuracy)} m</td><td>{r.session_id||r.share_epoch||r.source} / {r.sequence_number??'—'}</td><td>{new Date(r.received_at).toISOString()}</td></tr>)}</tbody></table></div><p>Times are UTC; CSV times are Unix milliseconds. Missing updates remain visible as gaps. Refreshing the table does not mean the agent has shared a new location.</p></>}</details>
}
