import {sqliteTable,text,integer,real,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const office=sqliteTable('office',{id:integer('id').primaryKey(),ownerId:text('owner_id').notNull(),ownerEmail:text('owner_email').notNull(),createdAt:integer('created_at').notNull()});
export const enquiries=sqliteTable('enquiries',{id:text('id').primaryKey(),name:text('name').notNull(),contact:text('contact').notNull(),interest:text('interest').notNull(),createdAt:integer('created_at').notNull(),status:text('status').notNull().default('new')});
export const visits=sqliteTable('visits',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),agentName:text('agent_name').notNull(),agentEmail:text('agent_email').notNull(),agentId:text('agent_id'),clientName:text('client_name').notNull(),property:text('property').notNull(),meeting:text('meeting').notNull(),lat:real('lat').notNull(),lng:real('lng').notNull(),scheduledAt:integer('scheduled_at').notNull(),expiresAt:integer('expires_at').notNull(),createdAt:integer('created_at').notNull(),inviteHash:text('invite_hash').notNull(),clientHash:text('client_hash').notNull(),status:text('status').notNull().default('scheduled'),consentAt:integer('consent_at'),consentVersion:text('consent_version'),shareStartedAt:integer('share_started_at'),shareEpoch:text('share_epoch'),shareUntil:integer('share_until'),activeDeviceId:text('active_device_id'),lastSequence:integer('last_sequence').default(-1),trackingHealth:text('tracking_health').default('idle'),lastReceivedAt:integer('last_received_at'),stoppedAt:integer('stopped_at'),revokedAt:integer('revoked_at'),etaMinutes:integer('eta_minutes'),clientConfirmedAt:integer('client_confirmed_at'),propertyConfirmed:text('property_confirmed'),clientComment:text('client_comment'),missingObservations:integer('missing_observations').default(0),healthReason:text('health_reason'),healthEvaluatedAt:integer('health_evaluated_at')},t=>[index('visits_owner').on(t.ownerId,t.createdAt),index('visits_agent').on(t.agentId,t.createdAt),index('visits_invite').on(t.inviteHash),index('visits_client').on(t.clientHash),index('visits_status').on(t.status,t.shareUntil)]);
export const points=sqliteTable('points',{id:text('id').primaryKey(),visitId:text('visit_id').notNull().references(()=>visits.id,{onDelete:'cascade'}),deviceId:text('device_id'),shareEpoch:text('share_epoch'),sequenceNumber:integer('sequence_number'),lat:real('lat').notNull(),lng:real('lng').notNull(),accuracy:real('accuracy').notNull(),altitude:real('altitude'),altitudeAccuracy:real('altitude_accuracy'),heading:real('heading'),speed:real('speed'),simulated:integer('simulated',{mode:'boolean'}).default(false),recordedAt:integer('recorded_at').notNull(),queuedAt:integer('queued_at'),receivedAt:integer('received_at').notNull(),qualityClass:text('quality_class'),plausibilityState:text('plausibility_state').default('normal'),payloadHash:text('payload_hash'),integrityFlags:text('integrity_flags')},t=>[index('points_visit_time').on(t.visitId,t.receivedAt),uniqueIndex('points_visit_epoch_sequence').on(t.visitId,t.shareEpoch,t.sequenceNumber)]);
export const devices=sqliteTable('devices',{id:text('id').primaryKey(),agentId:text('agent_id').notNull(),publicKeyJwk:text('public_key_jwk').notNull(),platform:text('platform').notNull(),appVersion:text('app_version'),createdAt:integer('created_at').notNull(),lastSeenAt:integer('last_seen_at').notNull(),revokedAt:integer('revoked_at')},t=>[index('devices_agent').on(t.agentId,t.lastSeenAt)]);
export const agentSessions=sqliteTable('agent_sessions',{id:text('id').primaryKey(),agentId:text('agent_id').notNull(),deviceId:text('device_id').notNull().references(()=>devices.id),startedAt:integer('started_at').notNull(),lastSeenAt:integer('last_seen_at').notNull(),endedAt:integer('ended_at')},t=>[index('agent_sessions_agent').on(t.agentId,t.lastSeenAt)]);
export const securityEvents=sqliteTable('security_events',{id:text('id').primaryKey(),agentId:text('agent_id').notNull(),deviceId:text('device_id').notNull().references(()=>devices.id),sessionId:text('session_id'),visitId:text('visit_id'),shareEpoch:text('share_epoch'),kind:text('kind').notNull(),deviceAt:integer('device_at').notNull(),receivedAt:integer('received_at').notNull(),detail:text('detail'),payloadHash:text('payload_hash').notNull()},t=>[index('security_events_agent_time').on(t.agentId,t.receivedAt),index('security_events_visit_time').on(t.visitId,t.receivedAt)]);
export const events=sqliteTable('events',{id:text('id').primaryKey(),visitId:text('visit_id').notNull().references(()=>visits.id,{onDelete:'cascade'}),kind:text('kind').notNull(),actor:text('actor').notNull(),at:integer('at').notNull(),detail:text('detail')},t=>[index('events_visit_time').on(t.visitId,t.at)]);
export const rateLimits=sqliteTable('rate_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expiresAt:integer('expires_at').notNull()});
export const observationRejections=sqliteTable('observation_rejections',{id:text('id').primaryKey(),visitId:text('visit_id').notNull().references(()=>visits.id,{onDelete:'cascade'}),deviceId:text('device_id').notNull(),shareEpoch:text('share_epoch').notNull(),sequenceNumber:integer('sequence_number').notNull(),code:text('code').notNull(),rawPayload:text('raw_payload'),payloadHash:text('payload_hash').notNull(),receivedAt:integer('received_at').notNull()},t=>[uniqueIndex('observation_rejections_visit_epoch_sequence').on(t.visitId,t.shareEpoch,t.sequenceNumber),index('observation_rejections_visit_time').on(t.visitId,t.receivedAt)]);
export const schemaMigrations=sqliteTable('schema_migrations',{version:text('version').primaryKey(),appliedAt:integer('applied_at').notNull()});
export const opsState=sqliteTable('ops_state',{key:text('key').primaryKey(),value:text('value').notNull(),updatedAt:integer('updated_at').notNull()});

export const agentAccounts=sqliteTable('agent_accounts',{id:text('id').primaryKey(),username:text('username').notNull(),email:text('email').notNull(),fullName:text('full_name').notNull(),passwordSalt:text('password_salt').notNull(),passwordHash:text('password_hash').notNull(),passwordIterations:integer('password_iterations').notNull(),active:integer('active',{mode:'boolean'}).notNull().default(true),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),lastLoginAt:integer('last_login_at')},t=>[uniqueIndex('agent_accounts_username').on(t.username),uniqueIndex('agent_accounts_email').on(t.email)]);
export const agentWebSessions=sqliteTable('agent_web_sessions',{tokenHash:text('token_hash').primaryKey(),agentId:text('agent_id').notNull().references(()=>agentAccounts.id,{onDelete:'cascade'}),createdAt:integer('created_at').notNull(),lastSeenAt:integer('last_seen_at').notNull(),expiresAt:integer('expires_at').notNull(),revokedAt:integer('revoked_at'),lastLat:real('last_lat'),lastLng:real('last_lng'),lastAccuracy:real('last_accuracy'),lastLocationAt:integer('last_location_at'),locationVerifiedAt:integer('location_verified_at'),currentPath:text('current_path'),currentPathSince:integer('current_path_since')},t=>[index('agent_web_sessions_agent').on(t.agentId,t.expiresAt),index('agent_web_sessions_expiry').on(t.expiresAt,t.revokedAt)]);

export const agentPageActivity=sqliteTable('agent_page_activity',{id:text('id').primaryKey(),agentId:text('agent_id').notNull().references(()=>agentAccounts.id,{onDelete:'cascade'}),sessionTokenHash:text('session_token_hash').notNull(),path:text('path').notNull(),kind:text('kind').notNull(),at:integer('at').notNull(),durationMs:integer('duration_ms').notNull().default(0),lat:real('lat').notNull(),lng:real('lng').notNull(),accuracy:real('accuracy').notNull()},t=>[index('agent_page_activity_agent_time').on(t.agentId,t.at),index('agent_page_activity_path_time').on(t.path,t.at)]);


export const agentOnboardingInvites=sqliteTable('agent_onboarding_invites',{id:text('id').primaryKey(),tokenHash:text('token_hash').notNull(),intendedEmail:text('intended_email'),status:text('status').notNull().default('issued'),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull(),openedAt:integer('opened_at'),submittedAt:integer('submitted_at'),revokedAt:integer('revoked_at')},t=>[uniqueIndex('agent_onboarding_invites_token').on(t.tokenHash),index('agent_onboarding_invites_status').on(t.status,t.expiresAt)]);
export const agentApplications=sqliteTable('agent_applications',{id:text('id').primaryKey(),inviteId:text('invite_id').notNull().references(()=>agentOnboardingInvites.id,{onDelete:'cascade'}),fullName:text('full_name'),email:text('email'),phone:text('phone'),city:text('city'),country:text('country'),currentCompany:text('current_company'),yearsExperience:integer('years_experience'),languagesJson:text('languages_json').notNull().default('[]'),marketsJson:text('markets_json').notNull().default('[]'),specialismsJson:text('specialisms_json').notNull().default('[]'),experienceSummary:text('experience_summary'),motivation:text('motivation'),status:text('status').notNull().default('draft'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),submittedAt:integer('submitted_at'),reviewedAt:integer('reviewed_at'),reviewedBy:text('reviewed_by'),reviewNote:text('review_note'),approvedAgentId:text('approved_agent_id').references(()=>agentAccounts.id,{onDelete:'set null'})},t=>[uniqueIndex('agent_applications_invite').on(t.inviteId),index('agent_applications_status').on(t.status,t.submittedAt)]);
export const agentScreeningSessions=sqliteTable('agent_screening_sessions',{id:text('id').primaryKey(),applicationId:text('application_id').notNull().references(()=>agentApplications.id,{onDelete:'cascade'}),version:text('version').notNull(),answersJson:text('answers_json').notNull().default('{}'),classificationJson:text('classification_json'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),completedAt:integer('completed_at')},t=>[uniqueIndex('agent_screening_sessions_application').on(t.applicationId)]);
