'use client';
export type LocationSample={lat:number;lng:number;accuracy:number;altitude:number|null;altitude_accuracy:number|null;heading:number|null;speed:number|null;simulated:boolean;recorded_at:number;source:'browser'|'native'};
export type ProviderMode='engaged'|'visit';
export interface LocationProvider{start(mode:ProviderMode,onPosition:(p:LocationSample)=>void,onError:(e:Error&{code?:number|string})=>void):Promise<void>;stop():Promise<void>;kind:string}
function sample(p:GeolocationPosition):LocationSample{return {lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,altitude:p.coords.altitude,altitude_accuracy:p.coords.altitudeAccuracy,heading:p.coords.heading,speed:p.coords.speed,simulated:false,recorded_at:p.timestamp,source:'browser'}}
export class BrowserLocationProvider implements LocationProvider{kind='browser';private watch:number|null=null;private heartbeat:ReturnType<typeof setInterval>|null=null;private wake:any=null;private generation=0;
async start(mode:ProviderMode,onPosition:(p:LocationSample)=>void,onError:(e:any)=>void){await this.stop();if(!window.isSecureContext||!navigator.geolocation)throw new Error('High-accuracy location requires HTTPS and a device location provider.');const generation=++this.generation;const options={enableHighAccuracy:true,maximumAge:0,timeout:20000};const first=await new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,options));if(generation!==this.generation)return;onPosition(sample(first));this.watch=navigator.geolocation.watchPosition(p=>generation===this.generation&&onPosition(sample(p)),e=>generation===this.generation&&onError(e),options);const interval=mode==='visit'?20000:60000;this.heartbeat=setInterval(()=>navigator.geolocation.getCurrentPosition(p=>generation===this.generation&&onPosition(sample(p)),e=>generation===this.generation&&onError(e),{...options,timeout:15000}),interval);if(mode==='visit')await this.acquireWakeLock();document.addEventListener('visibilitychange',this.visibility)}
private visibility=()=>{if(document.visibilityState==='visible'&&this.watch!==null)this.acquireWakeLock().catch(()=>{});else if(document.visibilityState==='hidden')this.releaseWakeLock().catch(()=>{})};
private async acquireWakeLock(){try{const w=(navigator as any).wakeLock;if(!w||document.visibilityState!=='visible'||this.wake)return;this.wake=await w.request('screen');this.wake.addEventListener?.('release',()=>{this.wake=null})}catch{}}
private async releaseWakeLock(){try{await this.wake?.release?.()}catch{}this.wake=null}
async stop(){this.generation++;if(this.watch!==null)navigator.geolocation?.clearWatch(this.watch);this.watch=null;if(this.heartbeat)clearInterval(this.heartbeat);this.heartbeat=null;document.removeEventListener('visibilitychange',this.visibility);await this.releaseWakeLock()}}
export async function probeBrowserLocation(){if(!window.isSecureContext||!navigator.geolocation)throw new Error('High-accuracy location requires HTTPS and a device location provider.');const p=await new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,maximumAge:0,timeout:20000}));return sample(p)}
