'use client';
export type QueuedObservation={id:string;scope:string;visit_id:string;share_epoch:string;sequence_number:number;lat:number;lng:number;accuracy:number;altitude:number|null;altitude_accuracy:number|null;heading:number|null;speed:number|null;simulated:boolean;recorded_at:number;queued_at:number;rejected_code?:string|null};
export type QueuedSecurityEvent={id:string;session_id:string;kind:string;device_at:number;visit_id?:string|null;share_epoch?:string|null;detail?:string|null;rejected_code?:string|null};
export type PendingTerminal={visit_id:string;share_epoch:string;device_id:string;action:'pause'|'arrive'|'complete';final_sequence:number;created_at:number};
type Meta={key:string;value:any};
type KeyRecord={id:string;privateKey:CryptoKey;publicJwk:JsonWebKey;deviceId:string};
const DB='private-office-telemetry-v2',VERSION=1;
let opening:Promise<IDBDatabase>|null=null;
function request<T>(r:IDBRequest<T>){return new Promise<T>((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('IndexedDB request failed.'))})}
function done(t:IDBTransaction){return new Promise<void>((resolve,reject)=>{t.oncomplete=()=>resolve();t.onabort=()=>reject(t.error||new Error('IndexedDB transaction aborted.'));t.onerror=()=>reject(t.error||new Error('IndexedDB transaction failed.'))})}
export function openTelemetryDb(){if(opening)return opening;opening=new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('meta'))d.createObjectStore('meta',{keyPath:'key'});if(!d.objectStoreNames.contains('keys'))d.createObjectStore('keys',{keyPath:'id'});if(!d.objectStoreNames.contains('observations')){const s=d.createObjectStore('observations',{keyPath:'id'});s.createIndex('scope_sequence',['scope','sequence_number'],{unique:true});s.createIndex('scope','scope');}if(!d.objectStoreNames.contains('security_events')){const s=d.createObjectStore('security_events',{keyPath:'id'});s.createIndex('session_time',['session_id','device_at']);}if(!d.objectStoreNames.contains('terminal_actions'))d.createObjectStore('terminal_actions',{keyPath:'visit_id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('Private Office local storage could not be opened.'))});return opening}
export async function getMeta<T=any>(key:string):Promise<T|null>{const d=await openTelemetryDb(),t=d.transaction('meta','readonly');const row=await request(t.objectStore('meta').get(key)) as Meta|undefined;await done(t);return row?.value??null}
export async function setMeta(key:string,value:any){const d=await openTelemetryDb(),t=d.transaction('meta','readwrite');t.objectStore('meta').put({key,value});await done(t)}
export async function delMeta(key:string){const d=await openTelemetryDb(),t=d.transaction('meta','readwrite');t.objectStore('meta').delete(key);await done(t)}
export async function nextSequence(scope:string){const key='seq:'+scope,d=await openTelemetryDb(),t=d.transaction('meta','readwrite'),s=t.objectStore('meta');const row=await request(s.get(key)) as Meta|undefined;const next=Number.isSafeInteger(row?.value)?Number(row!.value)+1:0;s.put({key,value:next});await done(t);return next}
export async function lastSequence(scope:string){const value=await getMeta<number>('seq:'+scope);return Number.isSafeInteger(value)?Number(value):-1}
export async function enqueueObservation(row:QueuedObservation){const d=await openTelemetryDb(),t=d.transaction('observations','readwrite');t.objectStore('observations').put(row);await done(t)}
export async function pendingObservations(scope?:string,limit=100){const d=await openTelemetryDb(),t=d.transaction('observations','readonly'),s=t.objectStore('observations');let rows:QueuedObservation[];if(scope){const range=IDBKeyRange.bound([scope,0],[scope,Number.MAX_SAFE_INTEGER]);rows=await request(s.index('scope_sequence').getAll(range,limit)) as QueuedObservation[]}else rows=await request(s.getAll()) as QueuedObservation[];await done(t);return rows.filter(r=>!r.rejected_code).slice(0,limit)}
export async function observationGroups(){const rows=await pendingObservations(undefined,5000),map=new Map<string,QueuedObservation[]>();for(const r of rows){const a=map.get(r.scope)||[];a.push(r);map.set(r.scope,a)}return [...map.values()].map(r=>r.sort((a,b)=>a.sequence_number-b.sequence_number))}
export async function countPending(scope?:string){return (await pendingObservations(scope,5000)).length}
export async function deleteObservations(ids:string[]){if(!ids.length)return;const d=await openTelemetryDb(),t=d.transaction('observations','readwrite'),s=t.objectStore('observations');for(const id of ids)s.delete(id);await done(t)}
export async function rejectObservations(rows:{id:string;code:string}[]){if(!rows.length)return;const d=await openTelemetryDb(),t=d.transaction('observations','readwrite'),s=t.objectStore('observations');for(const r of rows){const row=await request(s.get(r.id)) as QueuedObservation|undefined;if(row)s.put({...row,rejected_code:r.code})}await done(t)}
export async function enqueueSecurityEvent(row:QueuedSecurityEvent){const d=await openTelemetryDb(),t=d.transaction('security_events','readwrite');t.objectStore('security_events').put(row);await done(t)}
export async function pendingSecurityEvents(limit=100){const d=await openTelemetryDb(),t=d.transaction('security_events','readonly');const rows=await request(t.objectStore('security_events').getAll()) as QueuedSecurityEvent[];await done(t);return rows.filter(r=>!r.rejected_code).sort((a,b)=>a.device_at-b.device_at).slice(0,limit)}
export async function deleteSecurityEvents(ids:string[]){if(!ids.length)return;const d=await openTelemetryDb(),t=d.transaction('security_events','readwrite'),s=t.objectStore('security_events');for(const id of ids)s.delete(id);await done(t)}
export async function rejectSecurityEvents(rows:{id:string;code:string}[]){if(!rows.length)return;const d=await openTelemetryDb(),t=d.transaction('security_events','readwrite'),s=t.objectStore('security_events');for(const r of rows){const row=await request(s.get(r.id)) as QueuedSecurityEvent|undefined;if(row)s.put({...row,rejected_code:r.code})}await done(t)}
export async function putTerminalAction(row:PendingTerminal){const d=await openTelemetryDb(),t=d.transaction('terminal_actions','readwrite');t.objectStore('terminal_actions').put(row);await done(t)}
export async function terminalActions(){const d=await openTelemetryDb(),t=d.transaction('terminal_actions','readonly');const rows=await request(t.objectStore('terminal_actions').getAll()) as PendingTerminal[];await done(t);return rows}
export async function deleteTerminalAction(visitId:string){const d=await openTelemetryDb(),t=d.transaction('terminal_actions','readwrite');t.objectStore('terminal_actions').delete(visitId);await done(t)}
export async function getKeyRecord(){const d=await openTelemetryDb(),t=d.transaction('keys','readonly');const row=await request(t.objectStore('keys').get('device-signing')) as KeyRecord|undefined;await done(t);return row||null}
export async function putKeyRecord(row:KeyRecord){const d=await openTelemetryDb(),t=d.transaction('keys','readwrite');t.objectStore('keys').put({...row,id:'device-signing'});await done(t)}
