'use client';
import {post} from '@/lib/client';
import {deviceIdentity,enroll,signEnvelope,type DeviceIdentity} from './device';
import {BrowserLocationProvider,probeBrowserLocation,type LocationProvider,type LocationSample} from './location-provider';
import {countPending,delMeta,deleteObservations,deleteSecurityEvents,deleteTerminalAction,enqueueObservation,enqueueSecurityEvent,getMeta,lastSequence,nextSequence,observationGroups,pendingSecurityEvents,putTerminalAction,rejectObservations,rejectSecurityEvents,setMeta,terminalActions,type PendingTerminal,type QueuedObservation,type QueuedSecurityEvent} from './outbox';
import {qualityFromAccuracy} from './shared';
export type TrackingHealth='initializing'|'engaged'|'acquiring'|'healthy'|'offline'|'stale'|'permission_lost'|'pending_close'|'stopped'|'error';
export type TrackerSnapshot={health:TrackingHealth;provider:string;queueDepth:number;last?:LocationSample;message?:string};
type ActiveVisit={visitId:string;epoch:string;until:number;deviceId:string};
type Callbacks={onSnapshot?:(s:TrackerSnapshot)=>void;onObservation?:(p:LocationSample)=>void;onError?:(e:Error)=>void};
export class DurableTracker{private identity!:DeviceIdentity;private sessionId='';private provider:LocationProvider=new BrowserLocationProvider();private active:ActiveVisit|null=null;private timer:ReturnType<typeof setInterval>|null=null;private flushing:Promise<void>|null=null;private destroyed=false;private callbacks:Callbacks;private snapshot:TrackerSnapshot={health:'initializing',provider:'browser',queueDepth:0};
constructor(callbacks:Callbacks={}){this.callbacks=callbacks}
get deviceId(){return this.identity?.deviceId||''}get current(){return this.active}get state(){return this.snapshot}
private emit(patch:Partial<TrackerSnapshot>){this.snapshot={...this.snapshot,...patch};this.callbacks.onSnapshot?.(this.snapshot)}
async initialize(){this.identity=await deviceIdentity();this.sessionId=crypto.randomUUID();await enroll(this.identity,this.sessionId);await this.event('APP_OPEN',{user_agent:navigator.userAgent});this.installListeners();this.timer=setInterval(()=>this.flush().catch(e=>this.callbacks.onError?.(e)),5000);await this.reconcileTerminalActions();await this.flush();await this.startEngagedIfGranted();this.emit({health:this.active?'healthy':'engaged',provider:this.provider.kind});return {deviceId:this.deviceId,sessionId:this.sessionId}}
private installListeners(){window.addEventListener('online',this.online);window.addEventListener('offline',this.offline);document.addEventListener('visibilitychange',this.visibility)}
private online=()=>{this.event('NETWORK_ONLINE').catch(()=>{});this.emit({health:this.active?'healthy':'engaged'});this.flush().catch(()=>{});this.reconcileTerminalActions().catch(()=>{})};
private offline=()=>{this.event('NETWORK_OFFLINE').catch(()=>{});this.emit({health:'offline',message:'Location is being retained on this device until the network returns.'})};
private visibility=()=>{this.event(document.visibilityState==='visible'?'APP_FOREGROUND':'APP_BACKGROUND').catch(()=>{})};
async destroy(){this.destroyed=true;if(this.timer)clearInterval(this.timer);this.timer=null;window.removeEventListener('online',this.online);window.removeEventListener('offline',this.offline);document.removeEventListener('visibilitychange',this.visibility);await this.event('APP_WORKSPACE_CLOSED').catch(()=>{});if(!this.active)await this.provider.stop().catch(()=>{})}
async probe(){return probeBrowserLocation()}
async startEngagedIfGranted(){if(this.active||this.destroyed)return;try{const permissions=(navigator as any).permissions;if(permissions){const status=await permissions.query({name:'geolocation'});if(status.state!=='granted')return}await this.provider.start('engaged',p=>this.captureEngaged(p).catch(()=>{}),e=>this.providerError(e));this.emit({health:'engaged',message:'Private Office security session active.'});await this.event('ENGAGED_LOCATION_SERVICE_STARTED')}catch(e){await this.event('ENGAGED_LOCATION_SERVICE_UNAVAILABLE',{message:(e as Error).message}).catch(()=>{})}}
private async captureEngaged(p:LocationSample){this.callbacks.onObservation?.(p);this.emit({last:p});await this.event('ENGAGED_LOCATION',{lat:p.lat,lng:p.lng,accuracy:p.accuracy,recorded_at:p.recorded_at,quality:qualityFromAccuracy(p.accuracy),source:p.source})}
async activateVisit(visitId:string,epoch:string,until:number,initial?:LocationSample){await this.provider.stop();this.active={visitId,epoch,until,deviceId:this.deviceId};await setMeta('active_visit',this.active);this.emit({health:'acquiring',message:'Acquiring a high-confidence location…'});await this.event('VISIT_LOCATION_SERVICE_START',{visit_id:visitId,share_epoch:epoch},{visitId,epoch});if(initial)await this.captureVisit(initial);try{await this.provider.start('visit',p=>this.captureVisit(p).catch(e=>this.callbacks.onError?.(e)),e=>this.providerError(e));this.emit({health:navigator.onLine?'healthy':'offline',message:'Visit tracking service active.'})}catch(e){this.emit({health:'permission_lost',message:(e as Error).message});await this.event('LOCATION_SERVICE_START_FAILED',{message:(e as Error).message},{visitId,epoch});throw e}}
async resumeFromServer(visit:{id:string;status:string;share_epoch?:string;share_until?:number;active_device_id?:string}){if(visit.status!=='sharing'||!visit.share_epoch||!visit.share_until)return false;if(visit.active_device_id&&visit.active_device_id!==this.deviceId){this.emit({health:'error',message:'This tracking epoch belongs to another registered device.'});return false}if(this.active?.visitId===visit.id&&this.active.epoch===visit.share_epoch)return true;await this.activateVisit(visit.id,visit.share_epoch,visit.share_until);await this.event('VISIT_TRACKING_RESUMED',{reason:'workspace_reloaded'},{visitId:visit.id,epoch:visit.share_epoch});return true}
private providerError(e:any){const denied=e?.code===1||e?.code==='NOT_AUTHORIZED';this.emit({health:denied?'permission_lost':'stale',message:denied?'Location permission is unavailable.':'Waiting for a fresh device location.'});this.event(denied?'LOCATION_PERMISSION_LOST':'LOCATION_PROVIDER_ERROR',{code:e?.code??null,message:e?.message??'Location provider error'},this.active?{visitId:this.active.visitId,epoch:this.active.epoch}:undefined).catch(()=>{})}
private async captureVisit(p:LocationSample){const s=this.active;if(!s)return;if(Date.now()>s.until+60000){this.emit({health:'stale',message:'The visit tracking window has elapsed.'});return}const scope=s.visitId+':'+s.epoch,sequence=await nextSequence(scope);const row:QueuedObservation={id:crypto.randomUUID(),scope,visit_id:s.visitId,share_epoch:s.epoch,sequence_number:sequence,lat:p.lat,lng:p.lng,accuracy:p.accuracy,altitude:p.altitude,altitude_accuracy:p.altitude_accuracy,heading:p.heading,speed:p.speed,simulated:p.simulated,recorded_at:p.recorded_at,queued_at:Date.now()};await enqueueObservation(row);this.callbacks.onObservation?.(p);this.emit({last:p,health:navigator.onLine?'healthy':'offline',queueDepth:await countPending(scope),message:navigator.onLine?'Location secured locally and syncing.':'Location secured locally; network unavailable.'});await this.event('OBSERVATION_QUEUED',{sequence_number:sequence,accuracy:p.accuracy,quality:qualityFromAccuracy(p.accuracy)},{visitId:s.visitId,epoch:s.epoch});this.flush().catch(()=>{})}
async event(kind:string,detail?:unknown,scope?:{visitId:string;epoch:string}){if(!this.sessionId)return;const row:QueuedSecurityEvent={id:crypto.randomUUID(),session_id:this.sessionId,kind,device_at:Date.now(),visit_id:scope?.visitId||null,share_epoch:scope?.epoch||null,detail:detail===undefined?null:JSON.stringify(detail).slice(0,2000)};await enqueueSecurityEvent(row);if(navigator.onLine)this.flush().catch(()=>{})}
async flush(){if(this.flushing)return this.flushing;this.flushing=this.doFlush().finally(()=>{this.flushing=null});return this.flushing}
private async doFlush(){if(!navigator.onLine||!this.identity)return;await this.flushObservations();await this.flushEvents();this.emit({queueDepth:await countPending()})}
private async flushObservations(onlyScope?:string){const groups=await observationGroups();for(const group of groups){if(!group.length||onlyScope&&group[0].scope!==onlyScope)continue;for(let offset=0;offset<group.length;offset+=100){const batch=group.slice(offset,offset+100).map(({scope,rejected_code,...o})=>o);const first=group[offset];const envelope={device_id:this.deviceId,visit_id:first.visit_id,share_epoch:first.share_epoch,observations:batch};const signature=await signEnvelope(this.identity,envelope);try{const result=await post('/api/agent/visit/'+first.visit_id+'/observations',{device_id:this.deviceId,share_epoch:first.share_epoch,observations:batch,signature});await deleteObservations(result.processed_ids||[]);await rejectObservations(result.rejected||[]);if(result.rejected?.length)await this.event('OBSERVATION_BATCH_REJECTED',{rejected:result.rejected},{visitId:first.visit_id,epoch:first.share_epoch})}catch(e){const status=(e as Error&{status?:number}).status;if(status===409||status===410){this.emit({health:'stale',message:'The server no longer accepts this tracking epoch. Pending evidence remains on this device.'});return}throw e}}}}
private async flushEvents(){for(let i=0;i<40;i++){const rows=await pendingSecurityEvents(100);if(!rows.length)return;const sessionId=rows[0].session_id;const group=rows.filter(row=>row.session_id===sessionId).slice(0,100);const events=group.map(({rejected_code,...e})=>e);const envelope={device_id:this.deviceId,session_id:sessionId,events};const signature=await signEnvelope(this.identity,envelope);const result=await post('/api/agent/activity',{...envelope,signature});await deleteSecurityEvents(result.processed_ids||[]);await rejectSecurityEvents(result.rejected||[])}}
async requestTerminal(action:'pause'|'arrive'|'complete'){const s=this.active;if(!s)throw new Error('No active tracking epoch.');await this.provider.stop();const scope=s.visitId+':'+s.epoch,finalSequence=await lastSequence(scope);const pending:PendingTerminal={visit_id:s.visitId,share_epoch:s.epoch,device_id:this.deviceId,action,final_sequence:finalSequence,created_at:Date.now()};await putTerminalAction(pending);this.emit({health:'pending_close',message:'Collection stopped on this device. Confirming the final sequence with the office…'});await this.event('VISIT_TERMINAL_REQUESTED',{action,final_sequence:finalSequence},{visitId:s.visitId,epoch:s.epoch});const result=await this.tryTerminal(pending);if(result)await this.startEngagedIfGranted();return result}
private async tryTerminal(p:PendingTerminal){if(!navigator.onLine)return false;const scope=p.visit_id+':'+p.share_epoch;for(let i=0;i<20;i++){await this.flushObservations(scope);if(await countPending(scope)===0)break}if(await countPending(scope)>0)return false;try{await post('/api/agent/visit/'+p.visit_id,{action:p.action,device_id:p.device_id,epoch:p.share_epoch,final_sequence:p.final_sequence});await deleteTerminalAction(p.visit_id);const current=await getMeta<ActiveVisit>('active_visit');if(current?.visitId===p.visit_id&&current.epoch===p.share_epoch)await delMeta('active_visit');if(this.active?.visitId===p.visit_id&&this.active.epoch===p.share_epoch)this.active=null;this.emit({health:'stopped',message:'Final telemetry sequence confirmed by the office.'});await this.event('VISIT_TERMINAL_CONFIRMED',{action:p.action,final_sequence:p.final_sequence},{visitId:p.visit_id,epoch:p.share_epoch});return true}catch(e){const status=(e as Error&{status?:number}).status;if(status===409){this.emit({health:'pending_close',message:'The office is waiting for remaining telemetry. The close action will retry automatically.'});return false}throw e}}
async reconcileTerminalActions(){for(const action of await terminalActions())try{await this.tryTerminal(action)}catch(e){this.callbacks.onError?.(e as Error)}}
async pendingCount(){return countPending()}}
